from supabase import create_client, Client
from app.config import settings
import logging
import uuid
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

class SupabaseService:
    def __init__(self):
        # Prefer service role key for backend administration to bypass RLS
        url = settings.SUPABASE_URL
        service_role_key = settings.SUPABASE_SERVICE_ROLE_KEY
        key = service_role_key if self._is_real_credential(service_role_key) else settings.SUPABASE_KEY
        
        if not self._is_real_url(url) or not self._is_real_credential(key):
            logger.warning("Supabase URL or Key is not configured correctly. Service will operate in offline/mock mode.")
            self.client = None
        else:
            try:
                self.client: Client = create_client(url, key)
                logger.info("Supabase client initialized successfully.")
            except Exception as e:
                logger.error(f"Failed to initialize Supabase client: {str(e)}")
                self.client = None

    @staticmethod
    def _is_real_url(url: Optional[str]) -> bool:
        return bool(url and url.startswith("https://") and "your-supabase-project" not in url)

    @staticmethod
    def _is_real_credential(value: Optional[str]) -> bool:
        return bool(value and not value.startswith("your-supabase-") and value not in {"your_api_key_here"})

    def is_configured(self) -> bool:
        return self.client is not None

    def sync_user(self, uid: str, email: str, display_name: Optional[str]) -> Dict[str, Any]:
        """
        Ensures a user exists in the Supabase PostgreSQL 'users' table.
        Runs when a user signs in.
        """
        if not self.is_configured():
            logger.info(f"[Offline] Sync user: {uid} ({email})")
            return {"id": uid, "email": email, "display_name": display_name}
            
        try:
            new_user = {
                "id": uid,
                "email": email,
                "display_name": display_name
            }
            response = self.client.table("users").upsert(new_user, on_conflict="id").execute()
            if not response.data:
                raise RuntimeError("Supabase returned no user record after sync")
            return response.data[0]
        except Exception as e:
            logger.error(f"Database error syncing user {uid}: {str(e)}")
            raise RuntimeError(f"Could not sync user to Supabase: {str(e)}") from e

    def save_document(self, user_id: str, doc_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Saves metadata and experiment entries of a generated document to 'documents' table.
        """
        if not self.is_configured():
            logger.info(f"[Offline] Save document for user {user_id}")
            doc_data["id"] = str(uuid.uuid4())
            return doc_data
            
        try:
            doc_record = {
                "user_id": user_id,
                "course_code": doc_data.get("course_code"),
                "course_name": doc_data.get("course_name"),
                "student_name": doc_data.get("student_name"),
                "register_number": doc_data.get("register_number"),
                "department": doc_data.get("department"),
                "year": doc_data.get("year"),
                "semester": doc_data.get("semester"),
                "academic_year": doc_data.get("academic_year"),
                "faculty": doc_data.get("faculty"),
                "lab_name": doc_data.get("lab_name"),
                "institution": doc_data.get("institution"),
                "experiments": doc_data.get("experiments", []),
                "docx_url": doc_data.get("docx_url"),
                "pdf_url": doc_data.get("pdf_url")
            }
            
            # If editing existing document
            doc_id = doc_data.get("id")
            if doc_id:
                response = self.client.table("documents").update(doc_record).eq("id", doc_id).eq("user_id", user_id).execute()
            else:
                response = self.client.table("documents").insert(doc_record).execute()
                
            if not response.data:
                raise RuntimeError("Failed to insert/update document in database")
            return response.data[0]
        except Exception as e:
            logger.error(f"Database error saving document: {str(e)}")
            raise e

    def get_documents(self, user_id: str) -> List[Dict[str, Any]]:
        """
        Retrieves all documents generated by a user, ordered by last updated.
        """
        if not self.is_configured():
            logger.info(f"[Offline] Get documents for user {user_id}")
            return []
            
        try:
            response = self.client.table("documents").select("*").eq("user_id", user_id).order("updated_at", desc=True).execute()
            return response.data or []
        except Exception as e:
            logger.error(f"Database error fetching documents: {str(e)}")
            return []

    def get_document(self, doc_id: str, user_id: str) -> Optional[Dict[str, Any]]:
        """
        Retrieves a single document by its UUID.
        """
        if not self.is_configured():
            return None
            
        try:
            response = self.client.table("documents").select("*").eq("id", doc_id).eq("user_id", user_id).execute()
            return response.data[0] if response.data else None
        except Exception as e:
            logger.error(f"Database error fetching document {doc_id}: {str(e)}")
            return None

    def delete_document(self, doc_id: str, user_id: str) -> bool:
        """
        Deletes a document from the database.
        """
        if not self.is_configured():
            logger.info(f"[Offline] Delete document {doc_id}")
            return True
            
        try:
            # First fetch document to get stored storage URLs for cleanup if needed
            doc = self.get_document(doc_id, user_id)
            if not doc:
                return False
                
            # Delete from DB
            response = self.client.table("documents").delete().eq("id", doc_id).eq("user_id", user_id).execute()
            
            # Optionally clean up files from storage buckets here
            # For simplicity, we keep storage history or clean up using backend schedules
            
            return len(response.data) > 0
        except Exception as e:
            logger.error(f"Database error deleting document {doc_id}: {str(e)}")
            return False

    def upload_file(self, bucket: str, storage_path: str, file_data: bytes, content_type: str) -> str:
        """
        Uploads raw file bytes to Supabase Storage bucket and returns the public URL.
        """
        if not self.is_configured():
            logger.info(f"[Offline] Upload file to bucket '{bucket}' path '{storage_path}'")
            return f"https://mockstorage.local/{bucket}/{storage_path}"
            
        try:
            # Ensure bucket exists (or handles error if already exists/permissions issue)
            # Standard supabase-py client upload command:
            # Check if file exists, if so update/overwrite or remove first
            try:
                self.client.storage.from_(bucket).remove(storage_path)
            except Exception:
                pass # Ignore errors during removal attempts
                
            response = self.client.storage.from_(bucket).upload(
                path=storage_path,
                file=file_data,
                file_options={"content-type": content_type}
            )
            
            # Get the public URL of the uploaded file
            public_url_res = self.client.storage.from_(bucket).get_public_url(storage_path)
            return public_url_res
        except Exception as e:
            logger.error(f"Storage upload error to bucket '{bucket}' at path '{storage_path}': {str(e)}")
            raise RuntimeError(f"Failed to upload document to storage: {str(e)}")

    def log_download(self, user_id: str, document_id: str, file_type: str) -> bool:
        """
        Logs a record download transaction to the download history log.
        """
        if not self.is_configured():
            return True
            
        try:
            log_record = {
                "user_id": user_id,
                "document_id": document_id,
                "file_type": file_type
            }
            self.client.table("download_history").insert(log_record).execute()
            return True
        except Exception as e:
            logger.error(f"Database error logging download: {str(e)}")
            return False

# Singleton instance
supabase_service = SupabaseService()
