from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse, StreamingResponse
from typing import List, Dict, Any
import os
import io

from app.schemas.document import DocumentGenerateSchema
from app.services.auth_service import get_current_user
from app.services.document_service import document_service
from app.services.supabase_service import supabase_service

router = APIRouter(prefix="/documents", tags=["Documents"])

@router.post("/preview")
async def preview_document(
    payload: DocumentGenerateSchema,
    background_tasks: BackgroundTasks,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Generates a temporary PDF record preview in-memory and returns it as a file stream.
    All files (DOCX, PDF, QRs) are automatically cleaned up in background after delivery.
    """
    try:
        data_dict = payload.model_dump()
        # Generate the document and PDF in temp folder
        gen_result = document_service.generate_document(data_dict)
        
        pdf_path = gen_result["pdf_path"]
        
        # Schedule cleanup task to run after the response is sent
        background_tasks.add_task(document_service.clean_up_files, gen_result)
        
        return FileResponse(
            path=pdf_path,
            media_type="application/pdf",
            filename=f"preview_record.pdf"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Preview generation failed: {str(e)}")

@router.post("/generate")
async def generate_document(
    payload: DocumentGenerateSchema,
    background_tasks: BackgroundTasks,
    format: str = "json",
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Generates DOCX and PDF, uploads them to Supabase Storage (if format is 'json'),
    and saves the record in Supabase PostgreSQL, or streams the file format directly.
    """
    user_id = current_user.get("uid")
    data_dict = payload.model_dump()
    
    try:
        # 1. Generate local files
        gen_result = document_service.generate_document(data_dict)
        
        # Schedule cleanup of local temp files after this request completes
        background_tasks.add_task(document_service.clean_up_files, gen_result)
        
        docx_path = gen_result["docx_path"]
        pdf_path = gen_result["pdf_path"]
        unique_id = gen_result["unique_id"]
        
        if format == "docx":
            return FileResponse(
                path=docx_path,
                media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                filename=f"Lab_Record_{payload.course_code}.docx"
            )
        elif format == "pdf":
            return FileResponse(
                path=pdf_path,
                media_type="application/pdf",
                filename=f"Lab_Record_{payload.course_code}.pdf"
            )
        
        # 2. Upload to Supabase Storage if configured, otherwise use fallback mock URLs
        docx_url = f"mock_url_{unique_id}.docx"
        pdf_url = f"mock_url_{unique_id}.pdf"
        
        if supabase_service.is_configured():
            # Read files as bytes
            with open(docx_path, "rb") as f_docx:
                docx_bytes = f_docx.read()
            with open(pdf_path, "rb") as f_pdf:
                pdf_bytes = f_pdf.read()
                
            storage_dir = f"{user_id}/{unique_id}"
            docx_url = supabase_service.upload_file(
                bucket="lab-records",
                storage_path=f"{storage_dir}/record.docx",
                file_data=docx_bytes,
                content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
            )
            
            pdf_url = supabase_service.upload_file(
                bucket="lab-records",
                storage_path=f"{storage_dir}/record.pdf",
                file_data=pdf_bytes,
                content_type="application/pdf"
            )
            
        # 3. Save metadata to database
        db_data = {
            **data_dict,
            "docx_url": docx_url,
            "pdf_url": pdf_url
        }
        saved_record = supabase_service.save_document(user_id, db_data)
        
        return {
            "status": "success",
            "message": "Document generated and saved successfully",
            "record": saved_record
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Document generation and save failed: {str(e)}")

@router.get("")
async def list_documents(current_user: Dict[str, Any] = Depends(get_current_user)):
    """
    Returns list of all saved lab records generated by the authenticated user.
    """
    user_id = current_user.get("uid")
    try:
        documents = supabase_service.get_documents(user_id)
        return {"status": "success", "documents": documents}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch documents: {str(e)}")

@router.get("/{id}")
async def get_document_details(
    id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Returns details of a single saved lab record.
    """
    user_id = current_user.get("uid")
    doc = supabase_service.get_document(id, user_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
    return {"status": "success", "document": doc}

@router.delete("/{id}")
async def delete_document(
    id: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Deletes the saved lab record database metadata.
    """
    user_id = current_user.get("uid")
    success = supabase_service.delete_document(id, user_id)
    if not success:
        raise HTTPException(status_code=404, detail="Document not found or delete failed")
        
    return {"status": "success", "message": "Document deleted successfully"}

@router.post("/{id}/download-log")
async def log_document_download(
    id: str,
    file_type: str,
    current_user: Dict[str, Any] = Depends(get_current_user)
):
    """
    Logs document download history in the database.
    """
    user_id = current_user.get("uid")
    if file_type not in ["docx", "pdf"]:
        raise HTTPException(status_code=400, detail="Invalid file type. Must be 'docx' or 'pdf'")
        
    supabase_service.log_download(user_id, id, file_type)
    return {"status": "success", "message": "Download logged"}
